# Generated by Django 5.2.4 on 2025-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mailitm_fid", models.CharField(max_length=50, unique=True)),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                ("total_duration", models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mailitm_fid", models.CharField(db_index=True, max_length=50)),
                ("date", models.DateTimeField()),
                (
                    "event_type_cd",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "etablissement_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_etablissement_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("duration_to_next_step", models.DurationField(blank=True, null=True)),
            ],
            options={
                "unique_together": {
                    ("mailitm_fid", "date", "event_type_cd", "etablissement_postal")
                },
            },
        ),
    ]
