# Generated by Django 5.2.4 on 2025-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="alert_after_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
