# Generated by Django 5.2.4 on 2025-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_package_alert_after_success_package_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["mailitm_fid"], name="core_packag_mailitm_f693b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["status"], name="core_packag_status_9189da_idx"),
        ),
        migrations.AddIndex(
            model_name="packageevent",
            index=models.Index(
                fields=["mailitm_fid"], name="core_packag_mailitm_93a35a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packageevent",
            index=models.Index(fields=["date"], name="core_packag_date_71b40e_idx"),
        ),
    ]
