# Generated by Django 5.2.4 on 2025-09-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_package_core_packag_mailitm_f693b3_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_upw", models.IntegerField()),
                ("dest_upw", models.IntegerField()),
                ("actual_duration", models.DurationField()),
                ("allowed_duration", models.DurationField(null=True)),
                ("late", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.package"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["package"], name="core_packag_package_b0443d_idx"
                    ),
                    models.Index(
                        fields=["origin_upw", "dest_upw"],
                        name="core_packag_origin__787f2a_idx",
                    ),
                ],
            },
        ),
    ]
