# Generated by Django 5.2.6 on 2025-10-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_packagetransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportIStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('airport_pre_arrived_dispatches_count', models.IntegerField()),
                ('airport_items_delivered', models.IntegerField()),
                ('airport_items_delivered_after_one_fail', models.IntegerField()),
                ('airport_undelivered_items', models.IntegerField()),
                ('airport_delivery_rate', models.FloatField()),
                ('airport_on_time_delivery_rate', models.FloatField()),
                ('airport_items_exceeding_holding_time', models.IntegerField()),
                ('airport_items_blocked_in_customs', models.IntegerField()),
                ('airport_returned_items', models.IntegerField()),
                ('airport_consolidation_time', models.TextField()),
                ('airport_end_to_end_transit_time_average', models.FloatField()),
                ('airport_shipment_consolidation_time', models.TextField()),
                ('airport_unscanned_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alarm_code', models.CharField(choices=[('ALR001', 'Envois non réceptionnés après transmission'), ('ALR002', 'Envois en attente de distribution'), ('ALR003', 'Dépassement du délai de garde'), ('ALR004', 'Dépêche en attente de traitement – Centre Aéropostal HB'), ('ALR005', 'Dépêche non réceptionnée – Alger CPX'), ('ALR006', 'Envois non réceptionnés – CTNI'), ('ALR007', 'Incident d’exploitation – Absence d’événements'), ('ALR008', 'Délais de concentration excessifs')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('trigger_condition', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('action_required', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CPXStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpx_pre_arrived_dispatches_count', models.IntegerField()),
                ('cpx_items_delivered', models.IntegerField()),
                ('cpx_items_delivered_after_one_fail', models.IntegerField()),
                ('cpx_undelivered_items', models.IntegerField()),
                ('cpx_delivery_rate', models.FloatField()),
                ('cpx_on_time_delivery_rate', models.FloatField()),
                ('cpx_items_exceeding_holding_time', models.IntegerField()),
                ('cpx_items_blocked_in_customs', models.IntegerField()),
                ('cpx_returned_items', models.IntegerField()),
                ('cpx_consolidation_time', models.TextField()),
                ('cpx_end_to_end_transit_time_average', models.FloatField()),
                ('cpx_shipment_consolidation_time', models.TextField()),
                ('cpx_unscanned_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CTNIStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ctni_pre_arrived_dispatches_count', models.IntegerField()),
                ('ctni_items_delivered', models.IntegerField()),
                ('ctni_items_delivered_after_one_fail', models.IntegerField()),
                ('ctni_undelivered_items', models.IntegerField()),
                ('ctni_delivery_rate', models.FloatField()),
                ('ctni_on_time_delivery_rate', models.FloatField()),
                ('ctni_items_exceeding_holding_time', models.IntegerField()),
                ('ctni_items_blocked_in_customs', models.IntegerField()),
                ('ctni_returned_items', models.IntegerField()),
                ('ctni_consolidation_time', models.TextField()),
                ('ctni_end_to_end_transit_time_average', models.FloatField()),
                ('ctni_shipment_consolidation_time', models.TextField()),
                ('ctni_unscanned_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pre_arrived_dispatches_count', models.IntegerField()),
                ('items_delivered', models.IntegerField()),
                ('items_delivered_after_one_fail', models.IntegerField()),
                ('undelivered_items', models.IntegerField()),
                ('delivery_rate', models.FloatField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('items_exceeding_holding_time', models.IntegerField()),
                ('items_blocked_in_customs', models.IntegerField()),
                ('returned_items', models.IntegerField()),
                ('consolidation_time', models.TextField()),
                ('end_to_end_transit_time_average', models.FloatField()),
                ('shipment_consolidation_time', models.TextField()),
                ('unscanned_items', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='packageevent',
            name='etablissement_postal',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageevent',
            name='event_type_cd',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packageevent',
            name='next_etablissement_postal',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagetransition',
            name='dest_upw',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='packagetransition',
            name='origin_upw',
            field=models.IntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='KPIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['kpi_name', 'timestamp'], name='core_kpihis_kpi_nam_2bb5a0_idx')],
                'unique_together': {('kpi_name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='OfficeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.TextField()),
                ('office_id', models.TextField()),
                ('office_alternative_name', models.TextField()),
                ('pre_arrived_dispatches_count', models.IntegerField()),
                ('items_delivered', models.IntegerField()),
                ('undelivered_items', models.IntegerField()),
                ('alerts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alert')),
            ],
        ),
        migrations.CreateModel(
            name='StateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.TextField()),
                ('state_number', models.IntegerField()),
                ('state_id', models.TextField()),
                ('state_alternative_name', models.TextField()),
                ('pre_arrived_dispatches_count', models.IntegerField()),
                ('items_delivered', models.IntegerField()),
                ('undelivered_items', models.IntegerField()),
                ('alerts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alert')),
            ],
        ),
    ]
