# Generated by Django 5.2.6 on 2025-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_airportistats_alert_cpxstats_ctnistats_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportistats',
            name='airport_end_to_end_transit_time_average',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cpxstats',
            name='cpx_end_to_end_transit_time_average',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ctnistats',
            name='ctni_end_to_end_transit_time_average',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='end_to_end_transit_time_average',
            field=models.TextField(),
        ),
    ]
