# Generated by Django 5.2.6 on 2025-10-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_airportistats_airport_end_to_end_transit_time_average_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirportIStats',
            new_name='AirportStats',
        ),
    ]
