# Generated by Django 5.2.6 on 2025-10-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_airportistats_airportstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officestats',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='statestats',
            name='alerts',
        ),
        migrations.AddField(
            model_name='alert',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.officestats'),
        ),
        migrations.AddField(
            model_name='alert',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.statestats'),
        ),
    ]
