# Generated by Django 5.2.6 on 2025-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_officestats_alerts_remove_statestats_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
