# Generated by Django 5.2.6 on 2025-10-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alert_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='solved',
            new_name='acknowledged',
        ),
    ]
