# Generated by Django 5.2.6 on 2025-10-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_solved_alert_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='alert_after_seizure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='cities_after_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='failure_before_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='flag_seized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='hold_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recovered_after_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='seized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
