# Generated by Django 5.2.6 on 2025-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_package_alert_after_seizure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='last_event_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_event_type_cd',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
