# Generated by Django 5.2.6 on 2025-10-26 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_package_last_event_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
