# Generated by Django 5.2.6 on 2025-10-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dashboard_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Postal Office',
                'verbose_name_plural': 'Postal Offices',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_1', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('varname', models.CharField(blank=True, max_length=100, null=True)),
                ('nl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('iso', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=100)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='officestats',
            name='office_alternative_name',
        ),
        migrations.RemoveField(
            model_name='officestats',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='officestats',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='statestats',
            name='state_alternative_name',
        ),
        migrations.RemoveField(
            model_name='statestats',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='statestats',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='statestats',
            name='state_number',
        ),
        migrations.AlterField(
            model_name='officestats',
            name='items_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officestats',
            name='pre_arrived_dispatches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officestats',
            name='undelivered_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statestats',
            name='items_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statestats',
            name='pre_arrived_dispatches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statestats',
            name='undelivered_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.postaloffice'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.postaloffice'),
        ),
        migrations.AddField(
            model_name='postaloffice',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_offices', to='core.state'),
        ),
        migrations.AddField(
            model_name='statestats',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.state'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.state'),
        ),
    ]
