# Generated by Django 5.2.6 on 2025-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_postaloffice_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaloffice',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
