# Generated by Django 5.2.6 on 2025-10-28 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_postaloffice_name_alter_state_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=20)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_duration_seconds', models.FloatField(blank=True, null=True)),
                ('n_rows', models.IntegerField()),
                ('n_columns', models.IntegerField()),
                ('columns', models.JSONField()),
                ('missing_values_count', models.IntegerField()),
                ('missing_values_by_column', models.JSONField(blank=True, null=True)),
                ('unique_packages_count', models.IntegerField()),
                ('unique_event_types', models.IntegerField()),
                ('top_event_types', models.JSONField(blank=True, null=True)),
                ('earliest_date', models.DateTimeField(blank=True, null=True)),
                ('latest_date', models.DateTimeField(blank=True, null=True)),
                ('time_range_days', models.IntegerField(blank=True, null=True)),
                ('events_inserted', models.IntegerField()),
                ('packages_created', models.IntegerField()),
                ('packages_updated', models.IntegerField()),
                ('alerts_created', models.IntegerField()),
                ('cleaning_time_seconds', models.FloatField(blank=True, null=True)),
                ('avg_step_duration_seconds', models.FloatField(blank=True, null=True)),
                ('avg_total_duration_seconds', models.FloatField(blank=True, null=True)),
                ('rows_removed_duplicates', models.IntegerField(blank=True, null=True)),
                ('rows_removed_invalid', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
