# Generated by Django 5.2.6 on 2025-10-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_uploadmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageevent',
            name='next_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_events', to='core.postaloffice'),
        ),
        migrations.AddField(
            model_name='packageevent',
            name='next_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_events', to='core.state'),
        ),
        migrations.AddField(
            model_name='packageevent',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.postaloffice'),
        ),
        migrations.AddField(
            model_name='packageevent',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.package'),
        ),
        migrations.AddField(
            model_name='packageevent',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.state'),
        ),
    ]
