# Generated by Django 5.2.6 on 2025-10-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_packageevent_next_office_packageevent_next_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officestats',
            name='alert_after_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='avg_delivery_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officestats',
            name='avg_hold_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officestats',
            name='cities_after_failure_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='failure_before_success_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='recovered_after_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='seized_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officestats',
            name='total_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='alert_after_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='avg_delivery_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statestats',
            name='avg_hold_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statestats',
            name='cities_after_failure_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='failure_before_success_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='recovered_after_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='seized_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statestats',
            name='total_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officestats',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.postaloffice'),
        ),
        migrations.AlterField(
            model_name='statestats',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.state'),
        ),
    ]
