# Generated by Django 5.2.6 on 2025-10-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_officestats_alert_after_success_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_end_to_end_transit_time_average',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_items_blocked_in_customs',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_items_delivered',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_items_delivered_after_one_fail',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_items_exceeding_holding_time',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_pre_arrived_dispatches_count',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_returned_items',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_shipment_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_undelivered_items',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='cpx_unscanned_items',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_end_to_end_transit_time_average',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_items_blocked_in_customs',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_items_delivered',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_items_delivered_after_one_fail',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_items_exceeding_holding_time',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_pre_arrived_dispatches_count',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_returned_items',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_shipment_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_undelivered_items',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='ctni_unscanned_items',
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='alerts_triggered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='avg_holding_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='avg_items_per_bag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='avg_sorting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='damaged_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='delayed_arrivals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='incoming_bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='items_exceeding_holding_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='max_sorting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='median_holding_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='misrouted_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='outgoing_bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='seized_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='throughput_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='unprocessed_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='unscanned_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='alerts_triggered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='avg_holding_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='avg_items_per_bag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='avg_sorting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='damaged_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='delayed_arrivals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='incoming_bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='items_exceeding_holding_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='max_sorting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='median_holding_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='misrouted_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='outgoing_bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='seized_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='throughput_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='unprocessed_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='unscanned_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptacle_fid', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('last_known_location', models.CharField(blank=True, max_length=255, null=True)),
                ('first_event_date', models.DateTimeField(blank=True, null=True)),
                ('last_event_date', models.DateTimeField(blank=True, null=True)),
                ('events_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['receptacle_fid'], name='core_bag_recepta_2de5bd_idx'), models.Index(fields=['country'], name='core_bag_country_29c841_idx')],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.bag'),
        ),
        migrations.CreateModel(
            name='BagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptacle_fid', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateTimeField()),
                ('event_typecd', models.CharField(blank=True, max_length=50, null=True)),
                ('etablissement_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('nextetablissement_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('duration_to_next_step', models.DurationField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['receptacle_fid'], name='core_bageve_recepta_7d3ad1_idx'), models.Index(fields=['date'], name='core_bageve_date_fc240b_idx'), models.Index(fields=['country'], name='core_bageve_country_7ad5cd_idx')],
                'unique_together': {('receptacle_fid', 'date', 'event_typecd', 'etablissement_postal')},
            },
        ),
    ]
