# Generated by Django 5.2.6 on 2025-10-30 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cpxstats_cpx_consolidation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagevent',
            name='next_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag_next_events', to='core.postaloffice'),
        ),
        migrations.AddField(
            model_name='bagevent',
            name='next_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag_next_events', to='core.state'),
        ),
        migrations.AddField(
            model_name='bagevent',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag_events', to='core.postaloffice'),
        ),
        migrations.AddField(
            model_name='bagevent',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag_events', to='core.state'),
        ),
    ]
