# Generated by Django 5.2.6 on 2025-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bagevent_next_office_bagevent_next_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpxstats',
            name='avg_items_per_bag',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='damaged_items_count',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='delayed_arrivals_count',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='misrouted_items_count',
        ),
        migrations.RemoveField(
            model_name='cpxstats',
            name='outgoing_bags_count',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='avg_items_per_bag',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='damaged_items_count',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='delayed_arrivals_count',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='misrouted_items_count',
        ),
        migrations.RemoveField(
            model_name='ctnistats',
            name='outgoing_bags_count',
        ),
    ]
