# Generated by Django 5.2.6 on 2025-10-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_baguploadmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpxstats',
            name='avg_items_per_bag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='damaged_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='delayed_arrivals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='misrouted_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpxstats',
            name='outgoing_bags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='avg_items_per_bag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='damaged_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='delayed_arrivals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='misrouted_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctnistats',
            name='outgoing_bags_count',
            field=models.IntegerField(default=0),
        ),
    ]
