# Generated by Django 5.2.6 on 2025-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cpxstats_avg_items_per_bag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_end_to_end_transit_time_average',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_items_blocked_in_customs',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_items_delivered',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_items_delivered_after_one_fail',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_items_exceeding_holding_time',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_pre_arrived_dispatches_count',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_returned_items',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_shipment_consolidation_time',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_undelivered_items',
        ),
        migrations.RemoveField(
            model_name='airportstats',
            name='airport_unscanned_items',
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_bag_lifecycle_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_duration_to_delivery',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_duration_to_export',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_handling_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_transit_duration_domestic',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='avg_transit_duration_international',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_closed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_created_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_deleted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_in_customs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_modified_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_reopened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_sampled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_with_carrier_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_with_missing_country',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='bags_with_missing_next_office',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='domestic_bags_received_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='domestic_bags_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='international_bags_received_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='international_bags_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='international_vs_domestic_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airportstats',
            name='max_transit_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
